### ISSUE TITLE
bug in the empowerqosmanager

### ISSUE THREAD

**Issue by joncnet** [5g-empower/empower-lvap-agent#27]
I found a bug in the empowerqosmanager.

In the test scenario I have 1 LVAP and 0 VAPs.

At line 210 of file empowerqosmanager.cc, the "is_unique_lvap" function is called whenever broadcast packets are processed by the click element; this function returns false if an LVAP is present but it is not part of an VAP, resulting in the the packet being dropped.
Changing the behaviour of this part of the code fixed the issue, although a definitive fix should consider the bigger picture

**Comment by rriggio** [comment]
Fixed
