### ISSUE TITLE
Lvap agent build fails

### ISSUE THREAD

**Issue by Giwrgosyea** [5g-empower/empower-lvap-agent#4]
After make -j N(cores) i get:

Download failed.
--2017-03-08 18:02:13--  http://downloads.openwrt.org/sources/linux-3.18.44.tar.xz
Resolving downloads.openwrt.org (downloads.openwrt.org)... 78.24.191.177
Connecting to downloads.openwrt.org (downloads.openwrt.org)|78.24.191.177|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-08 18:02:13 ERROR 404: Not Found.

Download failed.
No more mirrors to try - giving up.

**Comment by rriggio** [comment]
Yes there are some problems with the openwrt mirrors. The only solution is to wait until they are fixed.
