### ISSUE TITLE
Change tx power

### ISSUE THREAD

**Issue by Giwrgosyea** [5g-empower/empower-lvap-agent#6]
Hello,
Is there any way to increase txpower of WTP? I tried by adding  option 'txpower' 'XX' on configuration file but nothing happend.

**Comment by rriggio** [comment]
that is a regular configuration option, the way of setting the power is the
correct one. if it is not applied it is not due to empower.

**Comment by Giwrgosyea** [comment]
I added this option in /etc/config/wireless but nothing happens and in /etc/config/empower nothing happens as well.

**Comment by rriggio** [comment]
But what did you expect to happen? I assume that the tx power is configured
for the interface and that's it.

**Comment by Giwrgosyea** [comment]
I want to increase/decrease txpower in order to decrease any interference between the WTPs.

**Comment by rriggio** [comment]
As I said the command is probably executed correctly by openwrt nothing in particular should happen on empower.
